//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ChatService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package chat;

public class Call implements java.lang.Cloneable,
                             java.io.Serializable
{
    public String callId;

    public String caller;

    public String callee;

    public boolean active;

    public long startedAt;

    public Call()
    {
        this.callId = "";
        this.caller = "";
        this.callee = "";
    }

    public Call(String callId, String caller, String callee, boolean active, long startedAt)
    {
        this.callId = callId;
        this.caller = caller;
        this.callee = callee;
        this.active = active;
        this.startedAt = startedAt;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Call r = null;
        if(rhs instanceof Call)
        {
            r = (Call)rhs;
        }

        if(r != null)
        {
            if(this.callId != r.callId)
            {
                if(this.callId == null || r.callId == null || !this.callId.equals(r.callId))
                {
                    return false;
                }
            }
            if(this.caller != r.caller)
            {
                if(this.caller == null || r.caller == null || !this.caller.equals(r.caller))
                {
                    return false;
                }
            }
            if(this.callee != r.callee)
            {
                if(this.callee == null || r.callee == null || !this.callee.equals(r.callee))
                {
                    return false;
                }
            }
            if(this.active != r.active)
            {
                return false;
            }
            if(this.startedAt != r.startedAt)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::chat::Call");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, callId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, caller);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, callee);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, active);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, startedAt);
        return h_;
    }

    public Call clone()
    {
        Call c = null;
        try
        {
            c = (Call)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.callId);
        ostr.writeString(this.caller);
        ostr.writeString(this.callee);
        ostr.writeBool(this.active);
        ostr.writeLong(this.startedAt);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.callId = istr.readString();
        this.caller = istr.readString();
        this.callee = istr.readString();
        this.active = istr.readBool();
        this.startedAt = istr.readLong();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Call v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Call ice_read(com.zeroc.Ice.InputStream istr)
    {
        Call v = new Call();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Call> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Call v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Call> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Call.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Call _nullMarshalValue = new Call();

    /** @hidden */
    public static final long serialVersionUID = -5886207083099289392L;
}
