//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ChatService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package chat;

/**
 * Helper class for marshaling/unmarshaling CallSeq.
 **/
public final class CallSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, Call[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                Call.ice_write(ostr, v[i0]);
            }
        }
    }

    public static Call[] read(com.zeroc.Ice.InputStream istr)
    {
        final Call[] v;
        final int len0 = istr.readAndCheckSeqSize(12);
        v = new Call[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = Call.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Call[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, Call[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            CallSeqHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<Call[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            Call[] v;
            v = CallSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
